version: "3.7"
services:
    #MariaDB Service
    database:
        image: mariadb
        container_name: jwt-maria
        tty: true
        user: "1000:1000"
        volumes:
            - ./docker/database:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: mysql_root_pass
            MYSQL_DATABASE: integracao
            MYSQL_USER: user_name
            MYSQL_PASSWORD: user_pass
        networks:
            - api-network
    #PHP Service
    php-fpm:
        build:
            context: ./docker
            dockerfile: Dockerfile
            args:
                uid: 1000
                gid: 1000
        container_name: jwt-php-fpm
        tty: true
        volumes:
            - ./api:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        working_dir: /var/www/html
        depends_on:
            - database
        networks:
           - api-network
    #Nginx Service
    server:
        image: nginx:alpine
        container_name: jwt-nginx
        tty: true
        ports:
            - 8001:80
            - 443:443
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-fpm
        networks:
            - api-network
#Docker Networks
networks:
    api-network:
        driver: bridge
